### ISSUE TITLE
CAD files

### ISSUE THREAD

**Issue by namaqualand** [elcrni/Voron-Mods#1]
Not really an issue. But I'd like to adapt the Voron PCB to your Orbiter 2.0 mount.
Is it possible to send the CAD files to me?

**Comment by jmceara** [comment]
I'm looking for this too! Will be very appreciated! :)

**Comment by elcrni** [comment]
CAD files will be uploaded soon. thanks

**Comment by elcrni** [comment]
CAD file uploaded! thanks
