### ISSUE TITLE
missing files for ebb36

### ISSUE THREAD

**Issue by MLeal91** [elcrni/Voron-Mods#12]
some files is missing comparative "beta files" like ebb36_cable_chain_anchor_3_hole is not in stl section files and Orbiter_2_Cable_Cover for ebb36 is missing
can you add this files?

**Comment by elcrni** [comment]
Oh, seems like i missed some, thanks for the tip, will add those shortly.

**Comment by MLeal91** [comment]
> Oh, seems like i missed some, thanks for the tip, will add those shortly.

files for ebb36 have changed?

**Comment by elcrni** [comment]
> > Oh, seems like i missed some, thanks for the tip, will add those shortly.
> 
> files for ebb36 have changed?

No, ebb files have not changed
