### ISSUE TITLE
Please consider changing screws to M3x25

### ISSUE THREAD

**Issue by bjensen** [elcrni/Voron-Mods#14]
Hi,

Is there a reason to why M3x26 is used instead of M3x25? The 25mm screws are already used in stealthburner and are much easier to source than 26mm.

![image](https://user-images.githubusercontent.com/53865/213582706-974fd465-7134-4b8c-9e03-ea5571e0a313.jpeg)

**Comment by elcrni** [comment]
hey, that was a typo, it is 25mm. thanks

**Comment by bjensen** [comment]
Have you tested the print ? I used 25mm screws and I couldn't get them to reach, thus I made this post

**Comment by elcrni** [comment]
Photos on the main page sort of show that i did test the print, heatset insert goes a tiny bit deeper and 25mm screw works just fine.

**Comment by bjensen** [comment]
You are right. You just have to supply enough pressure when inserting the screw. 

Let's close this issue and thanks for the prompt reply ✌️

**Comment by elcrni** [comment]
> You are right. You just have to supply enough pressure when inserting the screw.
> 
> Let's close this issue and thanks for the prompt reply ✌️

;-) thanks!
