### ISSUE TITLE
Orbiter: Too loose fit?

### ISSUE THREAD

**Issue by bjensen** [elcrni/Voron-Mods#16]
As you can seee in the attached video, it seams that the orbiter is able to wiggle in the mount..

https://user-images.githubusercontent.com/53865/213867329-f6936050-6efa-445d-b7c2-309bab3acb1c.mov

**Comment by tommy536** [comment]
This is not a normal behavior. Mine is absolutly solid.

**Comment by bjensen** [comment]
Did you reprint the newest version?

**Comment by tommy536** [comment]
> Did you reprint the newest version?
> 
> 

I printed the parts first time 3 days ago.

**Comment by elcrni** [comment]
> As you can seee in the attached video, it seams that the orbiter is able to wiggle in the mount..
> 
>  IMG_0531.mov

I am not sure how you got the orbiter to "wiggle". I have printed each and every iteration and tested everything, solid as a rock.

**Comment by bjensen** [comment]
Ah. I thought some screws

![image](https://user-images.githubusercontent.com/53865/213919888-631463a2-c91b-4807-9be0-6d7400fb14a2.jpeg)

**Comment by bjensen** [comment]
I had forgotten some screws ![image](https://user-images.githubusercontent.com/53865/213919936-ade44316-8201-42d2-8530-2b72e7a4f662.jpeg)

**Comment by elcrni** [comment]
> I had forgotten some screws ![image](https://user-images.githubusercontent.com/53865/213919936-ade44316-8201-42d2-8530-2b72e7a4f662.jpeg)

That happens. Perhaps avoid submitting an "issue" before you check everything first. thanks
