### ISSUE TITLE
Ebb36 Adapter mit working with tap 5v pcb

### ISSUE THREAD

**Issue by Malygros** [elcrni/Voron-Mods#18]
![924AAAD3-DB18-4F12-99B1-6D8EDB1EB3EA](https://user-images.githubusercontent.com/1886624/215569155-bf9b5b3f-a6d3-40b5-87de-ec6af009dd2b.jpeg)

  
![3C896B48-E294-4984-AC2B-9EAB465B4B3F](https://user-images.githubusercontent.com/1886624/215569600-446c987a-61b4-4217-b79c-82769ea58d94.jpeg)

Hey,
I got issues when installing the new ebb36 with tap pcb.

there is no manual for mounting but I think this must be the way.

when I install the ebb36 adapter it collide with tap pcb.

**Comment by tommy536** [comment]
This is the wrong side. The Umbi holder is mounted on the right when u look from behind. ![image](https://user-images.githubusercontent.com/45936061/215572364-29e569e1-8bef-458b-97da-440ab50b55d2.jpeg)

**Comment by Malygros** [comment]
> This is the wrong side. The Umbi holder is mounted on the right when u look from behind. ![image](https://user-images.githubusercontent.com/45936061/215572364-29e569e1-8bef-458b-97da-440ab50b55d2.jpeg)

Arg, That came never to my mind. Ty for the Info. Maybe the Readme should be updated :D

**Comment by tommy536** [comment]
I think it is to use so 😀 Bcs. umbi is the counterpart of the Chains. The lower position is also good. But, in the meantime i am using a another solution with the standard EBB Mounts for a Orbiter. At the Moment i cannot say if the hight is to much to the top panel.

**Comment by Malygros** [comment]
It works fine. Just installed everything. Will there be a Cover for the cables from EBB36 soon? PCB is not working.

**Comment by elcrni** [comment]
> It works fine. Just installed everything. Will there be a Cover for the cables from EBB36 soon? PCB is not working.

Correct cover for the EBB36 has been added to STL folder.
