### ISSUE TITLE
Clearance for heatset tool

### ISSUE THREAD

**Issue by eddietheengineer** [elcrni/Voron-Mods#2]
Hello @elcrni! Thanks for making this mod, it looks really well done! 

I've started printing the parts, but when I tried to insert the heatsets into the front piece, there wasn't enough clearance for the heatset insertion tool (I'm using LDO's), so it ended up melting the plastic:

![image](https://user-images.githubusercontent.com/11861478/192173049-ed8e0ed5-bc25-443b-ae65-f8a87d4ed2c1.png)

![image](https://user-images.githubusercontent.com/11861478/192173058-4a60d017-ee48-40be-b597-9a4718d64c77.png)

Also, consider opening up the back screw hole pass throughs for the NEMA14 motor mount! This would allow mounting of M3 standoffs to mount a CAN toolhead board such as the EBB 36 V1.2

![IMG_6369](https://user-images.githubusercontent.com/11861478/192173086-8ebf9bc3-15b8-41a8-ab34-ba49f02df1f3.jpg)

**Comment by elcrni** [comment]
@eddietheengineer thanks for the feedback. I am aware of the issue but for now that's the only way. I am using thinner soldering tip and have no issues and not touching the plastic. Will see if this can be avoided completely. many thanks

**Comment by mstawick** [comment]
@eddietheengineer FYI, maybe it's helpful to you, I've used these tips:
https://www.amazon.pl/dp/B09WPJ56JP/ref=pe_25095781_587317651_TE_item

and was able to embed the inserts cleanly.

**Comment by elcrni** [comment]
> @eddietheengineer FYI, maybe it's helpful to you, I've used these tips: https://www.amazon.pl/dp/B09WPJ56JP/ref=pe_25095781_587317651_TE_item
> 
> and was able to embed the inserts cleanly.

Awesome, thanks for the link!
