### ISSUE TITLE
Can't mount EBB36 and Cover Latch

### ISSUE THREAD

**Issue by erlis** [elcrni/Voron-Mods#21]
I saw two version of the cover and I've tried both, but I can't use it with the EBB, check picture below

![image](https://user-images.githubusercontent.com/137626/222988808-fb234f31-3da4-4718-bd04-731537c5c50e.png)

I can't find the cover with that on the files provided, I exported the cover from the CAD and I'm printing that to test one more time. I think I'm missing something because a lot of people are using the EBB board

**Comment by erlis** [comment]
UPDATE: After printing the file I exported from the CAD, the same one I'm pointing here, that cover works perfect with the EBB, I think it needs to be added on the STLs as COVER-FOR-EBB

**Comment by elcrni** [comment]
EBB cover has been added as the STL to the main repository. many thanks
