### ISSUE TITLE
Why is orbiter covered?

### ISSUE THREAD

**Issue by CD1010** [elcrni/Voron-Mods#22]
Orbiter is buried under useless plastic.  I don't get this stealthburner thing.  Can you come up with a EVA VORON mount instead?

**Comment by elcrni** [comment]
> Orbiter is buried under useless plastic. I don't get this stealthburner thing. Can you come up with a EVA VORON mount instead?

The beauty of making mods is the fact that anyone can make what THEY like, what THEY need, the way THEY want :-)
I've come up with this the way i like it, it's shared with everyone for free to use it by their own liking. I have no plans to make EVA mount. Thanks and have fun
