### ISSUE TITLE
Switchwire chain anchor

### ISSUE THREAD

**Issue by mstawick** [elcrni/Voron-Mods#3]
The SW anchor is slightly deeper, to centre the drag chain over the gantry profile. Could you include the STL for the switchwire as well? 

Thanks for the mod!

Edit:
I'm attaching my take on it; seems to be fine.

[chain_anchor_sw.zip](https://github.com/elcrni/Voron-Mods/files/9679544/chain_anchor_fixed.zip)

**Comment by elcrni** [comment]
hey, sorry for late reply. yes i will include it soon, sorting out other things. many thanks
