### ISSUE TITLE
CLOSED - Doesn't work LDO Orbiter 2

### ISSUE THREAD

**Issue by d4mer** [elcrni/Voron-Mods#30]
I can confirm that an LDO Orbiter 2 and GDStime fan doesn't fit with with this toolhead. I printed the deep version and it still doesn't work
![IMG_0471](https://github.com/elcrni/Voron-Mods/assets/6909228/9adaec49-b5de-45bc-8d7f-55353541fb25)
![IMG_0470](https://github.com/elcrni/Voron-Mods/assets/6909228/5d92d0d4-d831-4e5f-8c40-cd94aff41c25)
![IMG_0469](https://github.com/elcrni/Voron-Mods/assets/6909228/f3eab40e-084f-45ea-a07f-1999775f2288)
![IMG_0468](https://github.com/elcrni/Voron-Mods/assets/6909228/77ffad71-dc7c-48e0-95af-62b56f90d3fd)

**Comment by d4mer** [comment]
Not valid

**Comment by ssbb** [comment]
@d4mer Just wondering what changed for you? I think it's not deep enough in my case too (gdstime fan as well).

I been using the normal version for some time and recently printed the deep one. Things are improved but not that much. When I put the screws in - orbiter just pushes the fan and it's misaligned.

**Comment by ssbb** [comment]
Answering my own question - it seems like I didn't pushed the fan till the end. I had to sand it down quite a lot so it fits on the lower cutout.
