### ISSUE TITLE
LDO Toolhead PCB support

### ISSUE THREAD

**Issue by PuszInPusz** [elcrni/Voron-Mods#6]
Dear creator, do you think there is a way to incorporate the LDO toolhead pcb in your design? Sofar your Orbiter design is the best I saw but I don’t think it’s compatible with my Ldo toolhead.

**Comment by arfr** [comment]
@PuszInPusz please take a look at https://github.com/MotorDynamicsLab/LDOVoron2/tree/main/STLs/LDOSBCW2MountCover they adopted it, maybe you can do it too :)

**Comment by bjensen** [comment]
@PuszInPusz How did you end up mounting the LDO toolhead?

**Comment by PuszInPusz** [comment]
@bjensen Hey, I didn’t. Before the holidays I designed something but I didn’t like it because I couldn’t close the lid. Between the holidays I did nothing but I’ll maybe begin to redesign my first attempt next week.

**Comment by bjensen** [comment]
@PuszInPusz care to share your design? As @arfr pointed out it might be easier to increase the size of latch if you have made a good mount

**Comment by elcrni** [comment]
guys, LDO toolhead PCB should be taken from hartk, so identical to hartk SB PCB... in this case i have already made the mount for that PCB. just look under PCB topic

**Comment by arfr** [comment]
where?

**Comment by elcrni** [comment]
There are no plans to incorporate LDO toolhead PCB at the moment. HARTK1213 PCB can be used instead (Single piece PCB only)
