### ISSUE TITLE
PCB Support

### ISSUE THREAD

**Issue by Fragmon** [elcrni/Voron-Mods#7]
Hey, i see that you include the pcb in your step but you dont make a mount for this board. Do you already do this or have i remix your files for a pcb mount?

**Comment by elcrni** [comment]
Hi there, there is still no support for PCB due to the design of the Orbiter extruder itself, its very very tricky to place the toolhead PCB under the cover, i am still testing different variants but can not give any ETA. thanks

**Comment by elcrni** [comment]
PCB support is now in testing stage. The PCB has to go further back compared to CW2, but this should not be an issue.

Initial release files will be available soon for testing.

![image](https://user-images.githubusercontent.com/74976689/209853664-0a5bfa90-3e3b-424c-a693-4e8860f9b55f.png)
![image](https://user-images.githubusercontent.com/74976689/209853672-05b1ccea-80f0-4330-a3f7-5eaa6eaab257.png)
![image](https://user-images.githubusercontent.com/74976689/209853700-4898ac64-7d84-4d73-a1ec-ae253dcd0a85.png)

**Comment by elcrni** [comment]
Beta PCB mount files can be downloaded from here:
https://layerguru.com/wp-content/uploads/2022/12/Orbiter_2_SB_PCB_mount.zip

Feedback would be appreciated.

**Comment by PuszInPusz** [comment]
@elcrni is there maybe a way you do a LDO PCB support? I myself tried to remix but I have the same issue. Can’t manage to close the lid such that the „contouring“ stays seamless.

**Comment by bjensen** [comment]
@elcrni Can you please release the cad files? Its hard to see how the pcb mount is attached to the rest..

**Comment by Gaschtae** [comment]
Can somebody please reupload the Files? The website seems to be down right now.

**Comment by elcrni** [comment]
gloval outage for SiteGround servers, should be back online shortly

**Comment by Fragmon** [comment]
works for me. Only problem is, that the cable from the mainboard crash with the z chain when he goes from the y,x endstopp to the z endstopp. I solve this problem with an a y move after x,y to get space between the chain and the cable.

**Comment by elcrni** [comment]
> works for me. Only problem is, that the cable from the mainboard crash with the z chain when he goes from the y,x endstopp to the z endstopp. I solve this problem with an a y move after x,y to get space between the chain and the cable.

Unfortunately this is as far as the PCB can go forward. Some evade code may be necessary to prevent Microfit connector and wires touching Z chain as @Fragmon did.

**Comment by damianhw** [comment]
Does anyone know of a version compatible with 2 piece PCBs like the hartk one or the SB2240/2209 Canbus one? Not sure how it could work with the tension lever in the way though.

**Comment by elcrni** [comment]
> Does anyone know of a version compatible with 2 piece PCBs like the hartk one or the SB2240/2209 Canbus one? Not sure how it could work with the tension lever in the way though.

No, this is not possible, not just because of the lever but the fact that the front side of the orbiter is touching the part cooling fan, simply no space to place the fan PCB.
