### ISSUE TITLE
Misc issues with Orbiter 2.0 mount

### ISSUE THREAD

**Issue by bjensen** [elcrni/Voron-Mods#8]
First off: Thank you for making the mount for the orbiter 2.0. 

I have assembled it and I have some findings: 

1. The piece that is touching the Orbiter top, right where the entry of the filament is super snug. The ASA Im using is almost bent a little. I have tried to attached some images that displays the issue:

![IMG_0504](https://user-images.githubusercontent.com/53865/211111310-c31877e0-098c-4261-8890-c2986ceb6b05.jpeg)
![IMG_0503](https://user-images.githubusercontent.com/53865/211111487-8b7ba189-4b07-4469-b519-6497e0582a88.jpeg)

2. More details of which screws to use where. For example when looking at https://github.com/elcrni/Voron-Mods/blob/main/Orbiter_2.0_SB_CW2_Enclosed/Images/Orbiter_2.0_SB_CW2_Enclosed__006.jpg its not possible to see which mm screw should be used. 

3. More details on how to mount the PCB mount. Ive printed out the beta pieces but cannot see how it is attached, even though Ive been looking at the images in https://github.com/elcrni/Voron-Mods/issues/7. Perhaps if you were to include an image where the latch and the pcb is removed it would be more obvious to see.

Great idea using a normal M3 as tensioner screw

Thanks again

**Comment by elcrni** [comment]
hey, thanks for the feedback.

1. Yes, its a little snug but the goof thing is that the front body part can be shaved off a little for easier and roomier fit. this will be done in next iteration soon,
2. unfortunately i don't always have the time to annotate everything, hopefully will sort that out as well soon. As first aid, just do trial and error with the screw length :-)
3. image of the PCB mount attached, again lack of time to do everything but soon.
![image](https://user-images.githubusercontent.com/74976689/211113470-2508dbb0-140d-41c4-9b7c-4370a6f41245.png)

hope this helps, thanks.

**Comment by bjensen** [comment]
Thanks for your prompt reply. How about releasing the cad files? 

That is quickly done and i will be able to make a pull request with my suggested changes and see how things to together and so will others.

**Comment by elcrni** [comment]
soon, when the next revision is ready, by monday evening i hope

**Comment by elcrni** [comment]
This is fixed
